% MakeNewFigure related functions
function [] = CreateSlider(f,ax,CkBx,I,J,NoIm)
    txt = uicontrol(f, ...
        'Style', 'text', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'String', 'Image n ' + string(NoIm), ...
        'Units', 'normalized', ...
        'Position', [0.405,0.15,0.12,0.05] ...
        );
    if size(I,2) == 1
        return
    end
    uit = uicontrol(f, ...
        'Style', 'slider', ...
        'Tag', 'uitImage', ...
        'Min', 1, ...
        'Max', size(I,2), ...
        'Value', NoIm, ...
        'UserData', 1, ...
        'Units', 'normalized', ...
        'Position', [0.54,0.01,0.33,0.03] ...
        );
    addlistener(uit,'ContinuousValueChange', ...
        @(hObject,event) UpdateFromSlider(hObject,event,uit,txt,ax,CkBx,I,J) ...
        );
end
