% MakeNewFigure related functions
function [] = CreatePatch(axHisto,CBLDataX)
    xL = get(axHisto,'Xlim');
    yL = get(axHisto,'Ylim');
    CBL = patch(axHisto, ...
        [CBLDataX(1) xL(2) xL(2) CBLDataX(1)], ...
        [yL(1) yL(1) yL(2) yL(2)], ...
        'yellow', ...
        'FaceAlpha', 0.5, ...
        'Tag', 'CBL', ...
        'PickableParts', 'none' ...
        );
    try
        delete(findobj(axHisto,'Tag','LGD'));
    catch
    end
    lgdLine = line(nan, nan, 'Linestyle', 'none', 'Marker', 'none', 'Color', 'none');
    lgd = legend(axHisto,lgdLine,int2str(CBLDataX(1)), ...
        'Color', 'none', ...
        'TextColor', 'red', ...
        'Box', 'off', ...
        'FontSize', 14, ...
        'FontWeight', 'bold', ...
        'Tag', 'LGD' ...
        );
end
