% MakeNewFigure related functions
function [CkBx] = CreateCheckBox(f)
    CkBx = uicontrol(f, ...
        'Style', 'checkbox', ...
        'String', 'Threshold on coloc & scatter', ...
        'Units', 'normalized', ...
        'Position', [0.415,0.04,0.1,0.03] ...
        );
end
