% Callback from histo
function [] = mouseClick(I,axHisto,axImBw,CaseImage)
    try
        CBL2 = findobj(axHisto, 'Tag', 'CBL');
        delete(CBL2);
    catch
    end
    pointCoord = get(gca,'CurrentPoint');
    x = pointCoord(1,1);
    y = pointCoord(1,2);
    xL = get(gca,'Xlim');
    yL = get(gca,'Ylim');
    Xcoord = [x xL(2) xL(2) x];
    Ycoord = [yL(1) yL(1) yL(2) yL(2)];
    CBL = patch(Xcoord,Ycoord, ...
        'yellow', ...
        'FaceAlpha', 0.5, ...
        'Tag', 'CBL', ...
        'PickableParts', 'none' ...
        );
	
	if CaseImage == 1
		UpdateBw(I,x,axImBw,false);
        axImBw.Title.String = 'Threshold ch1';
	elseif CaseImage == 2
		UpdateBw(I,x,axImBw,false);
        axImBw.Title.String = 'Threshold ch2';
    end
    lgdLine = line(nan, nan, 'Linestyle', 'none', 'Marker', 'none', 'Color', 'none');
    lgd = legend(lgdLine,int2str(x), ...
        'Color', 'none', ...
        'TextColor', 'red', ...
        'Box', 'off', ...
        'FontSize', 14, ...
        'FontWeight', 'bold', ...
        'Tag', 'LGD' ...
        );
end
